#!/usr/bin/env python

import sys, subprocess
import readline
from string import ascii_lowercase, ascii_uppercase

readline.parse_and_bind("tab: complete")
commands = {}
showReturnStatus = False
showListAlways = False
useColour = False

def printColour(colour, msg):
	if colour == "red":
		print("\033[91m" + msg + "\033[0m")
	elif colour == "green":
		print("\033[92m" + msg + "\033[0m")
	else:
		print(msg)

def _get_key():
	used = commands.keys()

	for c in ascii_lowercase + ascii_uppercase:
		if c not in used:
			return c

	return None

def run(key):
	try:
		subprocess.check_call(commands[key], shell=True, stdout=sys.stdout, stderr=sys.stderr)
	except subprocess.CalledProcessError:
		if showReturnStatus == True:
			if useColour == True:
				printColour("red", "Return status code was non-zero.")
			else:
				print("Return status code was non-zero.")
		return False

	if showReturnStatus == True:
		if useColour == True:
			printColour("green", "Return status code was zero.")
		else:
			print("Return status code was zero.")
	return True

def edit(choice):
	parts = choice.split(" ", 1)
	if parts[-1] not in commands.keys():
		print("Selected command doesn't exist")
		return False

	value = input("Enter new command: ")
	commands[parts[-1]] = value

def add(choice):
	parts = choice.split(" ", 1)

	if len(parts) > 1:
		cmd = parts[-1]
	else:
		cmd = input("Enter command: ")

	commands[_get_key()] = cmd

def delete(choice):
	parts = choice.split(" ", 1)

	if len(parts) > 1:
		key = parts[-1]
	else:
		if showListAlways == False:
			_print_list()
		key = input("Which command? ")

	del commands[key]

def copy(choice):
	parts = choice.split(" ", 1)
	if parts[-1] not in commands.keys():
		print("Selected command doesn't exist")
		return False

	commands[_get_key()] = commands[parts[-1]]

def halp():
	print("(/a)dd [command]")
	print("(/d)elete [key]")
	print("(/h)elp")
	print("(/l)ist")
	print("(/r)unall")
	print("(/q)uit")


def _print_list():
	print("")
	for cmd in sorted(commands.items()):
		print("[%s] %s" % cmd)

def runall():
	for cmd in sorted(commands.items()):
		print("[%s] %s" % cmd)
		run(cmd[0])
		print("")

def loop():
	if showListAlways == True:
		_print_list()
	choice = input("> ")

	if choice.startswith("/d"):
		delete(choice)
	elif choice.startswith("/a"):
		add(choice)
	elif choice.startswith("/c"):
		copy(choice)
	elif choice.startswith("/e"):
		edit(choice)
	elif choice.startswith("/h"):
		halp()
	elif choice.startswith("/l"):
		_print_list()
	elif choice.startswith("/r"):
		runall()
	elif choice.startswith("/q"):
		return False
	elif not choice.strip():
		pass
	elif choice in commands.keys():
		run(choice)
	else:
		print("Derp?")

	return True


if __name__ == "__main__":
	if len(sys.argv) > 1:
		for x in range(1, len(sys.argv)):
			if sys.argv[x] == "-r":
				showReturnStatus = True
			elif sys.argv[x] == "-l":
				showListAlways = True
			elif sys.argv[x] == "-c":
				useColour = True

	try:
		while loop():
			pass
	except EOFError:
		pass
